# Generated by Django 3.0.7 on 2020-06-16 10:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20200616_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiddenreview',
            name='hidden_account',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), default=list, size=None),
        ),
    ]
