# Generated by Django 3.0.7 on 2020-06-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20200616_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reviews.review',),
        ),
        migrations.AlterField(
            model_name='review',
            name='moderated',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
